[package]
name = "stunnel"
version = "0.3.0"
authors = ["airtrack <airtrack.sk@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "*"
chrono = "0.4"
rand = "*"
log = { version = "*", features = ["std"] }
getopts = "0.2"
crc = "1.4.0"
async-std = { version = "1.0", features = ["unstable"] }
futures-timer = "1.0.2"
crossbeam-utils = "0.7"
futures = "0.3"
