socks5_listen = "0.0.0.0:1080"
http_listen = "0.0.0.0:8080"
server_addr = "127.0.0.1:12345"
server_name = "stunnel"
server_cert = "stunnel_cert.pem"
private_key = "private_key.pem"

# tlstcp or quic or s2n-quic
tunnel_type = "tlstcp"

# quic config for s2n-quic
# quic = { loss_threshold = 20 }

# logging to the ULS on macOS
# macos_logging = { enable = false, subsystem = "stunnel" }
